version: '2.2'
services:
  db:
    build:
      context: ../services/docker
      dockerfile: extended-postgres.dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-db:0.10-4d7eb06f5ae57e2b0b7686a3415bf165
        platforms:
          - linux/amd64
      x-hash-paths:
        - extended-postgres.dockerfile
  web:
    build:
      context: .
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-web:202-fc23af9dc264d8d4df652be9ec363d39
        platforms:
          - linux/amd64
      x-hash-paths:
        - requirements.txt
        - yarn.lock
