version: '2.2'
services:
  db:
    build:
      context: ../services/docker
      dockerfile: extended-postgres.dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-db:0.9-6a3784e44e500935d6ce57e13b485d78
        platforms:
          - linux/amd64
      x-hash-paths:
        - extended-postgres.dockerfile
  web:
    build:
      context: .
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-web:201-fdf2f8983653feb9b50312029729b3bd
        platforms:
          - linux/amd64
      x-hash-paths:
        - requirements.txt
        - yarn.lock
