version: '2.2'
services:
  db:
    build:
      context: ../services/docker
      dockerfile: extended-postgres.dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-db:0.8-bc582483e3741366137113cb651ba221
        platforms:
          - linux/amd64
      x-hash-paths:
        - extended-postgres.dockerfile
  web:
    build:
      context: .
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-web:193-d040527490ae6085aa7bb20db19c5397
        platforms:
          - linux/amd64
      x-hash-paths:
        - requirements.txt
        - yarn.lock
