version: '2.2'
services:
  db:
    build:
      context: ../services/docker
      dockerfile: extended-postgres.dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-db:0.11-87b1f75e23108920085920c6784796ff
        platforms:
          - linux/amd64
      x-hash-paths:
        - extended-postgres.dockerfile
  web:
    build:
      context: .
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-web:213-0ec1448a716f7e48d142dbe270c77d6b
        platforms:
          - linux/amd64
      x-hash-paths:
        - requirements.txt
        - yarn.lock
