version: '2.2'
services:
  db:
    build:
      context: ../services/docker
      dockerfile: extended-postgres.dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-db:0.13-355de4ae9825784849037c8870a24d41
        platforms:
          - linux/amd64
      x-hash-paths:
        - extended-postgres.dockerfile
  web:
    build:
      context: .
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-web:216-bda384e365b39a9c4c1d36f7e1502092
        platforms:
          - linux/amd64
      x-hash-paths:
        - requirements.txt
        - yarn.lock
